import Std.Tactic.BVDecide

namespace S2FlowsInLean
namespace SecondConjecture50BV

-- AUTO-GENERATED by scripts/generate_second50_bvdecide.py.
-- Source of truth for data: ALLOWED_VALUES, COORDS, TRIPLES in that script.

def bv8 (z : Int) : BitVec 8 :=
  BitVec.ofInt 8 z

def allConstraints (q0 : BitVec 8) (q1 : BitVec 8) (q2 : BitVec 8) (q3 : BitVec 8) (q4 : BitVec 8) (q5 : BitVec 8) (q6 : BitVec 8) (q7 : BitVec 8) (q8 : BitVec 8) (q9 : BitVec 8) (q10 : BitVec 8) (q11 : BitVec 8) (q12 : BitVec 8) (q13 : BitVec 8) (q14 : BitVec 8) (q15 : BitVec 8) (q16 : BitVec 8) (q17 : BitVec 8) (q18 : BitVec 8) (q19 : BitVec 8) (q20 : BitVec 8) (q21 : BitVec 8) (q22 : BitVec 8) (q23 : BitVec 8) (q24 : BitVec 8) (q25 : BitVec 8) (q26 : BitVec 8) (q27 : BitVec 8) (q28 : BitVec 8) (q29 : BitVec 8) (q30 : BitVec 8) (q31 : BitVec 8) (q32 : BitVec 8) (q33 : BitVec 8) (q34 : BitVec 8) (q35 : BitVec 8) (q36 : BitVec 8) (q37 : BitVec 8) (q38 : BitVec 8) (q39 : BitVec 8) (q40 : BitVec 8) (q41 : BitVec 8) (q42 : BitVec 8) (q43 : BitVec 8) (q44 : BitVec 8) (q45 : BitVec 8) (q46 : BitVec 8) (q47 : BitVec 8) (q48 : BitVec 8) (q49 : BitVec 8) : Bool :=
  ((q0 == bv8 (-4)) || (q0 == bv8 (-3)) || (q0 == bv8 (-2)) || (q0 == bv8 (-1)) || (q0 == bv8 (1)) || (q0 == bv8 (2)) || (q0 == bv8 (3)) || (q0 == bv8 (4))) &&
    ((q1 == bv8 (-4)) || (q1 == bv8 (-3)) || (q1 == bv8 (-2)) || (q1 == bv8 (-1)) || (q1 == bv8 (1)) || (q1 == bv8 (2)) || (q1 == bv8 (3)) || (q1 == bv8 (4))) &&
    ((q2 == bv8 (-4)) || (q2 == bv8 (-3)) || (q2 == bv8 (-2)) || (q2 == bv8 (-1)) || (q2 == bv8 (1)) || (q2 == bv8 (2)) || (q2 == bv8 (3)) || (q2 == bv8 (4))) &&
    ((q3 == bv8 (-4)) || (q3 == bv8 (-3)) || (q3 == bv8 (-2)) || (q3 == bv8 (-1)) || (q3 == bv8 (1)) || (q3 == bv8 (2)) || (q3 == bv8 (3)) || (q3 == bv8 (4))) &&
    ((q4 == bv8 (-4)) || (q4 == bv8 (-3)) || (q4 == bv8 (-2)) || (q4 == bv8 (-1)) || (q4 == bv8 (1)) || (q4 == bv8 (2)) || (q4 == bv8 (3)) || (q4 == bv8 (4))) &&
    ((q5 == bv8 (-4)) || (q5 == bv8 (-3)) || (q5 == bv8 (-2)) || (q5 == bv8 (-1)) || (q5 == bv8 (1)) || (q5 == bv8 (2)) || (q5 == bv8 (3)) || (q5 == bv8 (4))) &&
    ((q6 == bv8 (-4)) || (q6 == bv8 (-3)) || (q6 == bv8 (-2)) || (q6 == bv8 (-1)) || (q6 == bv8 (1)) || (q6 == bv8 (2)) || (q6 == bv8 (3)) || (q6 == bv8 (4))) &&
    ((q7 == bv8 (-4)) || (q7 == bv8 (-3)) || (q7 == bv8 (-2)) || (q7 == bv8 (-1)) || (q7 == bv8 (1)) || (q7 == bv8 (2)) || (q7 == bv8 (3)) || (q7 == bv8 (4))) &&
    ((q8 == bv8 (-4)) || (q8 == bv8 (-3)) || (q8 == bv8 (-2)) || (q8 == bv8 (-1)) || (q8 == bv8 (1)) || (q8 == bv8 (2)) || (q8 == bv8 (3)) || (q8 == bv8 (4))) &&
    ((q9 == bv8 (-4)) || (q9 == bv8 (-3)) || (q9 == bv8 (-2)) || (q9 == bv8 (-1)) || (q9 == bv8 (1)) || (q9 == bv8 (2)) || (q9 == bv8 (3)) || (q9 == bv8 (4))) &&
    ((q10 == bv8 (-4)) || (q10 == bv8 (-3)) || (q10 == bv8 (-2)) || (q10 == bv8 (-1)) || (q10 == bv8 (1)) || (q10 == bv8 (2)) || (q10 == bv8 (3)) || (q10 == bv8 (4))) &&
    ((q11 == bv8 (-4)) || (q11 == bv8 (-3)) || (q11 == bv8 (-2)) || (q11 == bv8 (-1)) || (q11 == bv8 (1)) || (q11 == bv8 (2)) || (q11 == bv8 (3)) || (q11 == bv8 (4))) &&
    ((q12 == bv8 (-4)) || (q12 == bv8 (-3)) || (q12 == bv8 (-2)) || (q12 == bv8 (-1)) || (q12 == bv8 (1)) || (q12 == bv8 (2)) || (q12 == bv8 (3)) || (q12 == bv8 (4))) &&
    ((q13 == bv8 (-4)) || (q13 == bv8 (-3)) || (q13 == bv8 (-2)) || (q13 == bv8 (-1)) || (q13 == bv8 (1)) || (q13 == bv8 (2)) || (q13 == bv8 (3)) || (q13 == bv8 (4))) &&
    ((q14 == bv8 (-4)) || (q14 == bv8 (-3)) || (q14 == bv8 (-2)) || (q14 == bv8 (-1)) || (q14 == bv8 (1)) || (q14 == bv8 (2)) || (q14 == bv8 (3)) || (q14 == bv8 (4))) &&
    ((q15 == bv8 (-4)) || (q15 == bv8 (-3)) || (q15 == bv8 (-2)) || (q15 == bv8 (-1)) || (q15 == bv8 (1)) || (q15 == bv8 (2)) || (q15 == bv8 (3)) || (q15 == bv8 (4))) &&
    ((q16 == bv8 (-4)) || (q16 == bv8 (-3)) || (q16 == bv8 (-2)) || (q16 == bv8 (-1)) || (q16 == bv8 (1)) || (q16 == bv8 (2)) || (q16 == bv8 (3)) || (q16 == bv8 (4))) &&
    ((q17 == bv8 (-4)) || (q17 == bv8 (-3)) || (q17 == bv8 (-2)) || (q17 == bv8 (-1)) || (q17 == bv8 (1)) || (q17 == bv8 (2)) || (q17 == bv8 (3)) || (q17 == bv8 (4))) &&
    ((q18 == bv8 (-4)) || (q18 == bv8 (-3)) || (q18 == bv8 (-2)) || (q18 == bv8 (-1)) || (q18 == bv8 (1)) || (q18 == bv8 (2)) || (q18 == bv8 (3)) || (q18 == bv8 (4))) &&
    ((q19 == bv8 (-4)) || (q19 == bv8 (-3)) || (q19 == bv8 (-2)) || (q19 == bv8 (-1)) || (q19 == bv8 (1)) || (q19 == bv8 (2)) || (q19 == bv8 (3)) || (q19 == bv8 (4))) &&
    ((q20 == bv8 (-4)) || (q20 == bv8 (-3)) || (q20 == bv8 (-2)) || (q20 == bv8 (-1)) || (q20 == bv8 (1)) || (q20 == bv8 (2)) || (q20 == bv8 (3)) || (q20 == bv8 (4))) &&
    ((q21 == bv8 (-4)) || (q21 == bv8 (-3)) || (q21 == bv8 (-2)) || (q21 == bv8 (-1)) || (q21 == bv8 (1)) || (q21 == bv8 (2)) || (q21 == bv8 (3)) || (q21 == bv8 (4))) &&
    ((q22 == bv8 (-4)) || (q22 == bv8 (-3)) || (q22 == bv8 (-2)) || (q22 == bv8 (-1)) || (q22 == bv8 (1)) || (q22 == bv8 (2)) || (q22 == bv8 (3)) || (q22 == bv8 (4))) &&
    ((q23 == bv8 (-4)) || (q23 == bv8 (-3)) || (q23 == bv8 (-2)) || (q23 == bv8 (-1)) || (q23 == bv8 (1)) || (q23 == bv8 (2)) || (q23 == bv8 (3)) || (q23 == bv8 (4))) &&
    ((q24 == bv8 (-4)) || (q24 == bv8 (-3)) || (q24 == bv8 (-2)) || (q24 == bv8 (-1)) || (q24 == bv8 (1)) || (q24 == bv8 (2)) || (q24 == bv8 (3)) || (q24 == bv8 (4))) &&
    ((q25 == bv8 (-4)) || (q25 == bv8 (-3)) || (q25 == bv8 (-2)) || (q25 == bv8 (-1)) || (q25 == bv8 (1)) || (q25 == bv8 (2)) || (q25 == bv8 (3)) || (q25 == bv8 (4))) &&
    ((q26 == bv8 (-4)) || (q26 == bv8 (-3)) || (q26 == bv8 (-2)) || (q26 == bv8 (-1)) || (q26 == bv8 (1)) || (q26 == bv8 (2)) || (q26 == bv8 (3)) || (q26 == bv8 (4))) &&
    ((q27 == bv8 (-4)) || (q27 == bv8 (-3)) || (q27 == bv8 (-2)) || (q27 == bv8 (-1)) || (q27 == bv8 (1)) || (q27 == bv8 (2)) || (q27 == bv8 (3)) || (q27 == bv8 (4))) &&
    ((q28 == bv8 (-4)) || (q28 == bv8 (-3)) || (q28 == bv8 (-2)) || (q28 == bv8 (-1)) || (q28 == bv8 (1)) || (q28 == bv8 (2)) || (q28 == bv8 (3)) || (q28 == bv8 (4))) &&
    ((q29 == bv8 (-4)) || (q29 == bv8 (-3)) || (q29 == bv8 (-2)) || (q29 == bv8 (-1)) || (q29 == bv8 (1)) || (q29 == bv8 (2)) || (q29 == bv8 (3)) || (q29 == bv8 (4))) &&
    ((q30 == bv8 (-4)) || (q30 == bv8 (-3)) || (q30 == bv8 (-2)) || (q30 == bv8 (-1)) || (q30 == bv8 (1)) || (q30 == bv8 (2)) || (q30 == bv8 (3)) || (q30 == bv8 (4))) &&
    ((q31 == bv8 (-4)) || (q31 == bv8 (-3)) || (q31 == bv8 (-2)) || (q31 == bv8 (-1)) || (q31 == bv8 (1)) || (q31 == bv8 (2)) || (q31 == bv8 (3)) || (q31 == bv8 (4))) &&
    ((q32 == bv8 (-4)) || (q32 == bv8 (-3)) || (q32 == bv8 (-2)) || (q32 == bv8 (-1)) || (q32 == bv8 (1)) || (q32 == bv8 (2)) || (q32 == bv8 (3)) || (q32 == bv8 (4))) &&
    ((q33 == bv8 (-4)) || (q33 == bv8 (-3)) || (q33 == bv8 (-2)) || (q33 == bv8 (-1)) || (q33 == bv8 (1)) || (q33 == bv8 (2)) || (q33 == bv8 (3)) || (q33 == bv8 (4))) &&
    ((q34 == bv8 (-4)) || (q34 == bv8 (-3)) || (q34 == bv8 (-2)) || (q34 == bv8 (-1)) || (q34 == bv8 (1)) || (q34 == bv8 (2)) || (q34 == bv8 (3)) || (q34 == bv8 (4))) &&
    ((q35 == bv8 (-4)) || (q35 == bv8 (-3)) || (q35 == bv8 (-2)) || (q35 == bv8 (-1)) || (q35 == bv8 (1)) || (q35 == bv8 (2)) || (q35 == bv8 (3)) || (q35 == bv8 (4))) &&
    ((q36 == bv8 (-4)) || (q36 == bv8 (-3)) || (q36 == bv8 (-2)) || (q36 == bv8 (-1)) || (q36 == bv8 (1)) || (q36 == bv8 (2)) || (q36 == bv8 (3)) || (q36 == bv8 (4))) &&
    ((q37 == bv8 (-4)) || (q37 == bv8 (-3)) || (q37 == bv8 (-2)) || (q37 == bv8 (-1)) || (q37 == bv8 (1)) || (q37 == bv8 (2)) || (q37 == bv8 (3)) || (q37 == bv8 (4))) &&
    ((q38 == bv8 (-4)) || (q38 == bv8 (-3)) || (q38 == bv8 (-2)) || (q38 == bv8 (-1)) || (q38 == bv8 (1)) || (q38 == bv8 (2)) || (q38 == bv8 (3)) || (q38 == bv8 (4))) &&
    ((q39 == bv8 (-4)) || (q39 == bv8 (-3)) || (q39 == bv8 (-2)) || (q39 == bv8 (-1)) || (q39 == bv8 (1)) || (q39 == bv8 (2)) || (q39 == bv8 (3)) || (q39 == bv8 (4))) &&
    ((q40 == bv8 (-4)) || (q40 == bv8 (-3)) || (q40 == bv8 (-2)) || (q40 == bv8 (-1)) || (q40 == bv8 (1)) || (q40 == bv8 (2)) || (q40 == bv8 (3)) || (q40 == bv8 (4))) &&
    ((q41 == bv8 (-4)) || (q41 == bv8 (-3)) || (q41 == bv8 (-2)) || (q41 == bv8 (-1)) || (q41 == bv8 (1)) || (q41 == bv8 (2)) || (q41 == bv8 (3)) || (q41 == bv8 (4))) &&
    ((q42 == bv8 (-4)) || (q42 == bv8 (-3)) || (q42 == bv8 (-2)) || (q42 == bv8 (-1)) || (q42 == bv8 (1)) || (q42 == bv8 (2)) || (q42 == bv8 (3)) || (q42 == bv8 (4))) &&
    ((q43 == bv8 (-4)) || (q43 == bv8 (-3)) || (q43 == bv8 (-2)) || (q43 == bv8 (-1)) || (q43 == bv8 (1)) || (q43 == bv8 (2)) || (q43 == bv8 (3)) || (q43 == bv8 (4))) &&
    ((q44 == bv8 (-4)) || (q44 == bv8 (-3)) || (q44 == bv8 (-2)) || (q44 == bv8 (-1)) || (q44 == bv8 (1)) || (q44 == bv8 (2)) || (q44 == bv8 (3)) || (q44 == bv8 (4))) &&
    ((q45 == bv8 (-4)) || (q45 == bv8 (-3)) || (q45 == bv8 (-2)) || (q45 == bv8 (-1)) || (q45 == bv8 (1)) || (q45 == bv8 (2)) || (q45 == bv8 (3)) || (q45 == bv8 (4))) &&
    ((q46 == bv8 (-4)) || (q46 == bv8 (-3)) || (q46 == bv8 (-2)) || (q46 == bv8 (-1)) || (q46 == bv8 (1)) || (q46 == bv8 (2)) || (q46 == bv8 (3)) || (q46 == bv8 (4))) &&
    ((q47 == bv8 (-4)) || (q47 == bv8 (-3)) || (q47 == bv8 (-2)) || (q47 == bv8 (-1)) || (q47 == bv8 (1)) || (q47 == bv8 (2)) || (q47 == bv8 (3)) || (q47 == bv8 (4))) &&
    ((q48 == bv8 (-4)) || (q48 == bv8 (-3)) || (q48 == bv8 (-2)) || (q48 == bv8 (-1)) || (q48 == bv8 (1)) || (q48 == bv8 (2)) || (q48 == bv8 (3)) || (q48 == bv8 (4))) &&
    ((q49 == bv8 (-4)) || (q49 == bv8 (-3)) || (q49 == bv8 (-2)) || (q49 == bv8 (-1)) || (q49 == bv8 (1)) || (q49 == bv8 (2)) || (q49 == bv8 (3)) || (q49 == bv8 (4))) &&
    (q12 == -q0) &&
    (q11 == -q1) &&
    (q10 == -q2) &&
    (q24 == -q3) &&
    (q19 == -q4) &&
    (q15 == -q5) &&
    (q31 == -q6) &&
    (q21 == -q7) &&
    (q41 == -q8) &&
    (q20 == -q9) &&
    (q17 == -q13) &&
    (q32 == -q14) &&
    (q35 == -q16) &&
    (q23 == -q18) &&
    (q44 == -q22) &&
    (q37 == -q25) &&
    (q48 == -q26) &&
    (q47 == -q27) &&
    (q49 == -q28) &&
    (q40 == -q29) &&
    (q39 == -q30) &&
    (q43 == -q33) &&
    (q46 == -q34) &&
    (q38 == -q36) &&
    (q45 == -q42) &&
    ((q41 + q25 + q42) == bv8 (0)) &&
    ((q18 + q19 + q12) == bv8 (0)) &&
    ((q49 + q19 + q40) == bv8 (0)) &&
    ((q22 + q37 + q34) == bv8 (0)) &&
    ((q10 + q11 + q12) == bv8 (0)) &&
    ((q0 + q4 + q23) == bv8 (0)) &&
    ((q29 + q4 + q28) == bv8 (0)) &&
    ((q48 + q37 + q24) == bv8 (0)) &&
    ((q33 + q9 + q2) == bv8 (0)) &&
    ((q20 + q19 + q21) == bv8 (0)) &&
    ((q6 + q39 + q40) == bv8 (0)) &&
    ((q11 + q35 + q42) == bv8 (0)) &&
    ((q7 + q4 + q9) == bv8 (0)) &&
    ((q6 + q7 + q8) == bv8 (0)) &&
    ((q29 + q30 + q31) == bv8 (0)) &&
    ((q41 + q21 + q31) == bv8 (0)) &&
    ((q35 + q38 + q47) == bv8 (0)) &&
    ((q32 + q26 + q2) == bv8 (0)) &&
    ((q0 + q1 + q2) == bv8 (0)) &&
    ((q10 + q27 + q28) == bv8 (0)) &&
    ((q45 + q16 + q1) == bv8 (0)) &&
    ((q10 + q48 + q14) == bv8 (0)) &&
    ((q33 + q16 + q34) == bv8 (0)) &&
    ((q6 + q22 + q23) == bv8 (0)) &&
    ((q3 + q25 + q26) == bv8 (0)) &&
    ((q18 + q44 + q31) == bv8 (0)) &&
    ((q15 + q16 + q17) == bv8 (0)) &&
    ((q10 + q20 + q43) == bv8 (0)) &&
    ((q46 + q35 + q43) == bv8 (0)) &&
    ((q6 + q13 + q14) == bv8 (0)) &&
    ((q45 + q37 + q8) == bv8 (0)) &&
    ((q37 + q38 + q30) == bv8 (0)) &&
    ((q27 + q36 + q16) == bv8 (0)) &&
    ((q13 + q35 + q5) == bv8 (0)) &&
    ((q49 + q47 + q2) == bv8 (0)) &&
    ((q15 + q19 + q24) == bv8 (0)) &&
    ((q3 + q4 + q5) == bv8 (0)) &&
    ((q32 + q17 + q31) == bv8 (0)) &&
    ((q39 + q36 + q25) == bv8 (0)) &&
    ((q46 + q25 + q44) == bv8 (0))

theorem allConstraints_false (q0 : BitVec 8) (q1 : BitVec 8) (q2 : BitVec 8) (q3 : BitVec 8) (q4 : BitVec 8) (q5 : BitVec 8) (q6 : BitVec 8) (q7 : BitVec 8) (q8 : BitVec 8) (q9 : BitVec 8) (q10 : BitVec 8) (q11 : BitVec 8) (q12 : BitVec 8) (q13 : BitVec 8) (q14 : BitVec 8) (q15 : BitVec 8) (q16 : BitVec 8) (q17 : BitVec 8) (q18 : BitVec 8) (q19 : BitVec 8) (q20 : BitVec 8) (q21 : BitVec 8) (q22 : BitVec 8) (q23 : BitVec 8) (q24 : BitVec 8) (q25 : BitVec 8) (q26 : BitVec 8) (q27 : BitVec 8) (q28 : BitVec 8) (q29 : BitVec 8) (q30 : BitVec 8) (q31 : BitVec 8) (q32 : BitVec 8) (q33 : BitVec 8) (q34 : BitVec 8) (q35 : BitVec 8) (q36 : BitVec 8) (q37 : BitVec 8) (q38 : BitVec 8) (q39 : BitVec 8) (q40 : BitVec 8) (q41 : BitVec 8) (q42 : BitVec 8) (q43 : BitVec 8) (q44 : BitVec 8) (q45 : BitVec 8) (q46 : BitVec 8) (q47 : BitVec 8) (q48 : BitVec 8) (q49 : BitVec 8) :
    allConstraints q0 q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12 q13 q14 q15 q16 q17 q18 q19 q20 q21 q22 q23 q24 q25 q26 q27 q28 q29 q30 q31 q32 q33 q34 q35 q36 q37 q38 q39 q40 q41 q42 q43 q44 q45 q46 q47 q48 q49 = false := by
  unfold allConstraints bv8
  bv_decide

theorem no_second50_labeling_bv :
    ¬ ∃ (q0 : BitVec 8) (q1 : BitVec 8) (q2 : BitVec 8) (q3 : BitVec 8) (q4 : BitVec 8) (q5 : BitVec 8) (q6 : BitVec 8) (q7 : BitVec 8) (q8 : BitVec 8) (q9 : BitVec 8) (q10 : BitVec 8) (q11 : BitVec 8) (q12 : BitVec 8) (q13 : BitVec 8) (q14 : BitVec 8) (q15 : BitVec 8) (q16 : BitVec 8) (q17 : BitVec 8) (q18 : BitVec 8) (q19 : BitVec 8) (q20 : BitVec 8) (q21 : BitVec 8) (q22 : BitVec 8) (q23 : BitVec 8) (q24 : BitVec 8) (q25 : BitVec 8) (q26 : BitVec 8) (q27 : BitVec 8) (q28 : BitVec 8) (q29 : BitVec 8) (q30 : BitVec 8) (q31 : BitVec 8) (q32 : BitVec 8) (q33 : BitVec 8) (q34 : BitVec 8) (q35 : BitVec 8) (q36 : BitVec 8) (q37 : BitVec 8) (q38 : BitVec 8) (q39 : BitVec 8) (q40 : BitVec 8) (q41 : BitVec 8) (q42 : BitVec 8) (q43 : BitVec 8) (q44 : BitVec 8) (q45 : BitVec 8) (q46 : BitVec 8) (q47 : BitVec 8) (q48 : BitVec 8) (q49 : BitVec 8), allConstraints q0 q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12 q13 q14 q15 q16 q17 q18 q19 q20 q21 q22 q23 q24 q25 q26 q27 q28 q29 q30 q31 q32 q33 q34 q35 q36 q37 q38 q39 q40 q41 q42 q43 q44 q45 q46 q47 q48 q49 = true := by
  intro h
  rcases h with ⟨q0, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, q12, q13, q14, q15, q16, q17, q18, q19, q20, q21, q22, q23, q24, q25, q26, q27, q28, q29, q30, q31, q32, q33, q34, q35, q36, q37, q38, q39, q40, q41, q42, q43, q44, q45, q46, q47, q48, q49, hC⟩
  have hFalse : allConstraints q0 q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12 q13 q14 q15 q16 q17 q18 q19 q20 q21 q22 q23 q24 q25 q26 q27 q28 q29 q30 q31 q32 q33 q34 q35 q36 q37 q38 q39 q40 q41 q42 q43 q44 q45 q46 q47 q48 q49 = false :=
    allConstraints_false q0 q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12 q13 q14 q15 q16 q17 q18 q19 q20 q21 q22 q23 q24 q25 q26 q27 q28 q29 q30 q31 q32 q33 q34 q35 q36 q37 q38 q39 q40 q41 q42 q43 q44 q45 q46 q47 q48 q49
  have hImpossible : (true : Bool) = false := by
    exact hC ▸ hFalse
  cases hImpossible

end SecondConjecture50BV
end S2FlowsInLean
