#!/usr/bin/env python3
"""Generate S2FlowsInLean/SecondConjecture50BVDecide.lean.

This script derives antipodal pairs from symbolic coordinates and emits a
fully expanded BitVec/Bool formula suitable for `bv_decide`.
"""

from __future__ import annotations

from pathlib import Path

N = 50

ALLOWED_VALUES = [-4, -3, -2, -1, 1, 2, 3, 4]

COORDS = {
    0: ("y+phi-1", "-(x-1)", "-phi"),
    1: ("-(y-1)", "x+phi", "phi-1"),
    2: ("-phi", "-(phi+1)", "1"),
    3: ("phi+1", "-1", "-phi"),
    4: ("0", "0", "2*phi"),
    5: ("-(phi+1)", "1", "-phi"),
    6: ("phi", "phi+1", "1"),
    7: ("y-phi+1", "-(x+1)", "-phi"),
    8: ("-(y+1)", "-(phi-x)", "phi-1"),
    9: ("-(y-phi+1)", "x+1", "-phi"),
    10: ("phi", "phi+1", "-1"),
    11: ("y-1", "-(x+phi)", "-(phi-1)"),
    12: ("-(y+phi-1)", "x-1", "phi"),
    13: ("phi", "-(phi+1)", "-1"),
    14: ("-2*phi", "0", "0"),
    15: ("phi+1", "-1", "phi"),
    16: ("-1", "-phi", "-(phi+1)"),
    17: ("-phi", "phi+1", "1"),
    18: ("y+phi-1", "-(x-1)", "phi"),
    19: ("0", "0", "-2*phi"),
    20: ("y-phi+1", "-(x+1)", "phi"),
    21: ("-(y-phi+1)", "x+1", "phi"),
    22: ("y-1", "-(x+phi)", "phi-1"),
    23: ("-(y+phi-1)", "x-1", "-phi"),
    24: ("-(phi+1)", "1", "phi"),
    25: ("-1", "-phi", "phi+1"),
    26: ("-phi", "phi+1", "-1"),
    27: ("1", "-phi", "phi+1"),
    28: ("-(phi+1)", "-1", "-phi"),
    29: ("phi+1", "1", "-phi"),
    30: ("-1", "phi", "phi+1"),
    31: ("-phi", "-(phi+1)", "-1"),
    32: ("2*phi", "0", "0"),
    33: ("y+1", "phi-x", "phi-1"),
    34: ("-y", "x", "2"),
    35: ("1", "phi", "phi+1"),
    36: ("0", "2*phi", "0"),
    37: ("1", "phi", "-(phi+1)"),
    38: ("0", "-2*phi", "0"),
    39: ("1", "-phi", "-(phi+1)"),
    40: ("-(phi+1)", "-1", "phi"),
    41: ("y+1", "phi-x", "-(phi-1)"),
    42: ("-y", "x", "-2"),
    43: ("-(y+1)", "-(phi-x)", "-(phi-1)"),
    44: ("-(y-1)", "x+phi", "-(phi-1)"),
    45: ("y", "-x", "2"),
    46: ("y", "-x", "-2"),
    47: ("-1", "phi", "-(phi+1)"),
    48: ("phi", "-(phi+1)", "1"),
    49: ("phi+1", "1", "phi"),
}

TRIPLES = [
    (41, 25, 42),
    (18, 19, 12),
    (49, 19, 40),
    (22, 37, 34),
    (10, 11, 12),
    (0, 4, 23),
    (29, 4, 28),
    (48, 37, 24),
    (33, 9, 2),
    (20, 19, 21),
    (6, 39, 40),
    (11, 35, 42),
    (7, 4, 9),
    (6, 7, 8),
    (29, 30, 31),
    (41, 21, 31),
    (35, 38, 47),
    (32, 26, 2),
    (0, 1, 2),
    (10, 27, 28),
    (45, 16, 1),
    (10, 48, 14),
    (33, 16, 34),
    (6, 22, 23),
    (3, 25, 26),
    (18, 44, 31),
    (15, 16, 17),
    (10, 20, 43),
    (46, 35, 43),
    (6, 13, 14),
    (45, 37, 8),
    (37, 38, 30),
    (27, 36, 16),
    (13, 35, 5),
    (49, 47, 2),
    (15, 19, 24),
    (3, 4, 5),
    (32, 17, 31),
    (39, 36, 25),
    (46, 25, 44),
]


def negate_expr(expr: str) -> str:
    expr = expr.strip()
    if expr == "0":
        return "0"
    if expr.startswith("-(") and expr.endswith(")"):
        return expr[2:-1]
    if expr.startswith("-"):
        return expr[1:]
    if "+" in expr or "-" in expr:
        return f"-({expr})"
    return f"-{expr}"


def derive_antipode_pairs() -> list[tuple[int, int]]:
    by_coord = {coord: i for i, coord in COORDS.items()}
    if len(by_coord) != N:
        raise ValueError("Coordinates are not unique")

    antipode: dict[int, int] = {}
    for i in range(N):
        neg_coord = tuple(negate_expr(x) for x in COORDS[i])
        if neg_coord not in by_coord:
            raise ValueError(f"Missing antipode for {i}: {neg_coord}")
        antipode[i] = by_coord[neg_coord]

    for i in range(N):
        j = antipode[i]
        if antipode[j] != i:
            raise ValueError(f"Not involutive: {i} -> {j} -> {antipode[j]}")

    return sorted((i, antipode[i]) for i in range(N) if i < antipode[i])


def const(z: int) -> str:
    return f"bv8 ({z})"


def emit() -> str:
    pairs = derive_antipode_pairs()

    qs = [f"q{i}" for i in range(N)]
    params = " ".join(f"(q{i} : BitVec 8)" for i in range(N))
    args = " ".join(qs)
    exists_binders = " ".join(f"(q{i} : BitVec 8)" for i in range(N))
    rcases_vars = ", ".join(qs + ["hC"])

    allowed_clauses = []
    for q in qs:
        parts = [f"({q} == {const(v)})" for v in ALLOWED_VALUES]
        allowed_clauses.append("(" + " || ".join(parts) + ")")

    antipode_clauses = [f"(q{b} == -q{a})" for a, b in pairs]
    triple_clauses = [f"((q{a} + q{b} + q{c}) == {const(0)})" for a, b, c in TRIPLES]

    all_clauses = allowed_clauses + antipode_clauses + triple_clauses
    formula = " &&\n    ".join(all_clauses)

    return f'''import Std.Tactic.BVDecide

namespace S2FlowsInLean
namespace SecondConjecture50BV

-- AUTO-GENERATED by scripts/generate_second50_bvdecide.py.
-- Source of truth for data: ALLOWED_VALUES, COORDS, TRIPLES in that script.

def bv8 (z : Int) : BitVec 8 :=
  BitVec.ofInt 8 z

def allConstraints {params} : Bool :=
  {formula}

theorem allConstraints_false {params} :
    allConstraints {args} = false := by
  unfold allConstraints bv8
  bv_decide

theorem no_second50_labeling_bv :
    ¬ ∃ {exists_binders}, allConstraints {args} = true := by
  intro h
  rcases h with ⟨{rcases_vars}⟩
  have hFalse : allConstraints {args} = false :=
    allConstraints_false {args}
  have hImpossible : (true : Bool) = false := by
    exact hC ▸ hFalse
  cases hImpossible

end SecondConjecture50BV
end S2FlowsInLean
'''


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "S2FlowsInLean" / "SecondConjecture50BVDecide.lean"
    out.write_text(emit(), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
